### ISSUE TITLE
error with pip install

### ISSUE THREAD

**Issue by jsykora** [NetAngels/django-webodt#1]
I've tried using pip on 3 different ubuntu machines (10.10 server, 10.10 desktop, 11.04 desktop) and each one fails with the following traceback:

<code>Downloading/unpacking django-webodt
  Downloading django-webodt-0.2.tar.gz
  Running setup.py egg_info for package django-webodt
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/username/build/django-webodt/setup.py", line 17, in <module>
        long_description = open('README.rst').read().decode('utf8'),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/username/build/django-webodt/setup.py", line 17, in <module>
    long_description = open('README.rst').read().decode('utf8'),
IOError: [Errno 2] No such file or directory: 'README.rst'
Command python setup.py egg_info failed with error code 1</code>

I'm not sure if it's a problem with the pip build missing the readme or just something coincidently wrong with all 3 of the machines I've tried.

**Comment by imankulov** [comment]
Thank you for your report.

It really seems like a bug in our setup.py. To work this around, you can install latest version of the package directly from github as 

```
pip install -e git://github.com/NetAngels/django-webodt.git#egg=django-webodt
```

Latest version has some undocumented (yet) features such as `TEMPLATE_PREPROCESSORS` but I think nothing should prevent you from using the package as described in the documentation. I hope this workaround is acceptable for you. We will fix the issue in a new version when documentation will have been completed.

**Comment by jsykora** [comment]
Cool that worked fine. I'll just leave this issue open and you can close it whenever you implement the fix to the setup.py file. Thanks for the help
