### ISSUE TITLE
Missing \n in AbiwordODFConverter

### ISSUE THREAD

**Issue by adamglowacki** [NetAngels/django-webodt#11]
Method convert() from AbiwordODFConverter seems to produce empty files. I think it is because of no \n character ending command for abiword in 18 line (webodt/converters/abiword.py). Without this \n abiword does not process the file. At least in my case. Sorry if I'm wrong.

**Comment by imankulov** [comment]
Thank you for the report, Adam. Can you please specify which version of abiword do you use. I will try to reproduce.

**Comment by adamglowacki** [comment]
I am surprised with such a quick reply. I have abiword 2.8.6 from opensuse.

2012/6/1 Roman Imankulov <
reply@reply.github.com

**Comment by imankulov** [comment]
Unfortunately, I didn' t manage to build 2.8.6 on my system so I cannot reproduce your bug. The one installed on my computer is 2.9.1, and everything seems to work.

Can you please specify one more thing. Have you tried to add "\n" to the code and succeeded with it? If it really solves your issue, there is no problem for me to make this minor modification. If you didn't try to fix it that way, please try and let me know what is the outcome.

Thank you.

**Comment by adamglowacki** [comment]
I've tried to use webodt but conversion yielded empty files. I looked into
the code and tried to do the same in python shell. I was able to see the
stdout of subprocess. When I put just 'convert %s %s %s' ... to
communicate, then there was no OK at the end of the abiword output. When I
called communicate with 'convert %s %s %s \n' ... I was able to see OK at
the end of the output and files were really converted.

2012/6/1 Roman Imankulov <
reply@reply.github.com

**Comment by imankulov** [comment]
Added missing "\n" in 992121d692f62f74d1f616205fa5ad0e18997ad4. Please try it out.

**Comment by adamglowacki** [comment]
Now it works! Thank you very much.

2012/6/1 Roman Imankulov <
reply@reply.github.com

**Comment by imankulov** [comment]
Thank you for your investigation and fix. I hope you enjoy.
