### ISSUE TITLE
com.sun.star.connection.NoConnectException

### ISSUE THREAD

**Issue by angebouabre** [NetAngels/django-webodt#18]
Hi guys!!
I try to django-webodt to generate documents, but i see there's no more feed on the project. Is it still stable? I try your example in package but i get this error with Open Office backend:

Connector : couldn't connect to socket (Success)
# line unocontext = resolver.resolve('uno:%s' % OOO_CONNECTION) in openoffice.py!

Thank you for your help

**Comment by imankulov** [comment]
Hi @angebouabre 

Thank you for your interest to the project. Unfortunately, it's not actively maintained now, and I'm afraid we don't have resources to investigate and fix the bug ourselves.

Although in your case, the issue may be trivial to resolve. Haven't your forgotten to start up the OpenOffice "server" as described [in the documentation](http://pythonhosted.org//django-webodt/backends.html#openoffice-openoffice-backend)?

**Comment by angebouabre** [comment]
@imankulov Thank you for your fast answer!!
Indeed i had forgotten to start the OpenOffice server like this...
I started and it works fine now!
Thank you!
