### ISSUE TITLE
WEBODT_ABIWORD_COMMAND option is ignored

### ISSUE THREAD

**Issue by mattaustin** [NetAngels/django-webodt#6]
The documentation refers to WEBODT_ABIWORD_COMMAND in order to specify a custom command for AbiWord. However, although converters/abiword.py imports this option, it ignores it and specifies WEBODT_ABIWORD_COMMAND = ['/usr/bin/abiword', '--plugin', 'AbiCommand'] in the code.

**Comment by imankulov** [comment]
My bad. Thank you for the report.
